name: obolus-execute-transfers
owner: obolus-protocol
triggers:
  - type: cron
    config:
      schedule: "*/15 * * * * *"  # Every 15 seconds
consensus:
  - type: offchain_consensus
    config:
      aggregation_method: AGGREGATION_MODE
      aggregation_config:
        allowedFaultPercent: 0
      encoder: EVM
      encoder_config:
        abi: "(bytes report)"
targets:
  - type: write_chain
    config:
      deltaStage: "10s"
      schedule: "oneAtATime"
